from __future__ import annotations

import ast
import operator
from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Any, ClassVar

from teachx.knowledge.service import KnowledgeService


class ToolError(ValueError):
    pass


@dataclass(slots=True, frozen=True)
class ToolContext:
    """Runtime context that is not generated by the model."""

    session_id: str = ""
    knowledge_bases: tuple[str, ...] = ()


@dataclass(slots=True)
class ToolResult:
    content: str
    success: bool = True
    metadata: dict[str, Any] | None = None


class BaseTool(ABC):
    """A model-callable unit with metadata and one execution method."""

    name: ClassVar[str]
    description: ClassVar[str]
    parameters: ClassVar[dict[str, Any]]

    def schema(self) -> dict[str, Any]:
        return {
            "type": "function",
            "function": {
                "name": self.name,
                "description": self.description,
                "parameters": self.parameters,
            },
        }

    @abstractmethod
    async def execute(
        self,
        context: ToolContext | None = None,
        **kwargs: Any,
    ) -> ToolResult:
        raise NotImplementedError


class CalculatorTool(BaseTool):
    name = "calculator"
    description = "Evaluate a basic arithmetic expression safely."
    parameters = {
        "type": "object",
        "properties": {
            "expression": {
                "type": "string",
                "description": "Arithmetic expression using +, -, *, /, and parentheses.",
            }
        },
        "required": ["expression"],
        "additionalProperties": False,
    }

    _binary_operators: ClassVar[dict[type[ast.operator], Any]] = {
        ast.Add: operator.add,
        ast.Sub: operator.sub,
        ast.Mult: operator.mul,
        ast.Div: operator.truediv,
        ast.Mod: operator.mod,
        ast.Pow: operator.pow,
    }
    _unary_operators: ClassVar[dict[type[ast.unaryop], Any]] = {
        ast.UAdd: operator.pos,
        ast.USub: operator.neg,
    }

    async def execute(
        self,
        context: ToolContext | None = None,
        **kwargs: Any,
    ) -> ToolResult:
        del context
        expression = str(kwargs.get("expression") or "").strip()
        if not expression:
            raise ToolError("expression is required")
        try:
            tree = ast.parse(expression, mode="eval")
            value = self._evaluate(tree.body)
        except (SyntaxError, TypeError, ZeroDivisionError, ToolError) as exc:
            raise ToolError(f"invalid expression: {exc}") from exc
        return ToolResult(content=str(value), metadata={"expression": expression})

    def _evaluate(self, node: ast.AST) -> int | float:
        if isinstance(node, ast.Constant) and isinstance(node.value, (int, float)):
            return node.value
        if isinstance(node, ast.BinOp) and type(node.op) in self._binary_operators:
            return self._binary_operators[type(node.op)](
                self._evaluate(node.left),
                self._evaluate(node.right),
            )
        if isinstance(node, ast.UnaryOp) and type(node.op) in self._unary_operators:
            return self._unary_operators[type(node.op)](self._evaluate(node.operand))
        raise ToolError(f"unsupported syntax: {type(node).__name__}")


class KnowledgeSearchTool(BaseTool):
    name = "knowledge_search"
    description = (
        "Search the learner's selected knowledge bases and return relevant "
        "source snippets with citations."
    )
    parameters = {
        "type": "object",
        "properties": {
            "query": {
                "type": "string",
                "description": "A focused natural-language search query.",
            },
            "knowledge_bases": {
                "type": "array",
                "items": {"type": "string"},
                "description": "Optional knowledge base names. Omit to use the current selection.",
            },
            "limit": {
                "type": "integer",
                "minimum": 1,
                "maximum": 10,
                "description": "Maximum number of source snippets.",
            },
        },
        "required": ["query"],
        "additionalProperties": False,
    }

    def __init__(self, service: KnowledgeService) -> None:
        self.service = service

    async def execute(
        self,
        context: ToolContext | None = None,
        **kwargs: Any,
    ) -> ToolResult:
        query = str(kwargs.get("query") or "").strip()
        if not query:
            raise ToolError("query is required")
        requested_bases = kwargs.get("knowledge_bases")
        if isinstance(requested_bases, list):
            knowledge_bases = [str(name) for name in requested_bases]
        else:
            knowledge_bases = list(context.knowledge_bases if context else ())
        limit = int(kwargs.get("limit") or 5)
        hits = await self.service.search(
            query,
            knowledge_bases,
            limit=limit,
        )
        if not hits:
            return ToolResult(
                content="知识库中没有找到与该问题相关的资料。",
                metadata={"sources": [], "query": query},
            )

        formatted = []
        sources = []
        for index, hit in enumerate(hits, start=1):
            citation = f"{hit.document} · 片段 {hit.chunk_index + 1}"
            formatted.append(
                f"[{index}] 知识库：{hit.knowledge_base}\n来源：{citation}\n内容：{hit.content}"
            )
            sources.append(
                {
                    "id": f"{hit.knowledge_base}:{hit.document}:{hit.chunk_index}",
                    "title": hit.document,
                    "knowledge_base": hit.knowledge_base,
                    "chunk_index": hit.chunk_index,
                    "snippet": hit.content,
                    "score": hit.score,
                }
            )
        return ToolResult(
            content="\n\n---\n\n".join(formatted),
            metadata={"sources": sources, "query": query},
        )


class ToolRegistry:
    def __init__(self) -> None:
        self._tools: dict[str, BaseTool] = {}

    def register(self, tool: BaseTool) -> None:
        self._tools[tool.name] = tool

    def get(self, name: str) -> BaseTool | None:
        return self._tools.get(name)

    def schemas(self, enabled: list[str] | None = None) -> list[dict[str, Any]]:
        names = enabled if enabled is not None else list(self._tools)
        return [self._tools[name].schema() for name in names if name in self._tools]

    async def execute(
        self,
        name: str,
        arguments: dict[str, Any],
        context: ToolContext | None = None,
    ) -> ToolResult:
        tool = self.get(name)
        if tool is None:
            return ToolResult(content=f"Unknown tool: {name}", success=False)
        try:
            return await tool.execute(context=context, **arguments)
        except Exception as exc:  # one bad tool must not kill the whole turn
            return ToolResult(content=f"Tool {name} failed: {exc}", success=False)


def build_default_registry(knowledge_service: KnowledgeService) -> ToolRegistry:
    registry = ToolRegistry()
    registry.register(CalculatorTool())
    registry.register(KnowledgeSearchTool(knowledge_service))
    return registry
