from __future__ import annotations

import ast
import asyncio
import operator
import sqlite3
import time
from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Any, ClassVar

from teachx.knowledge.service import KnowledgeService
from teachx.runtime.tool_executions import (
    ToolExecutionRecord,
    ToolExecutionStore,
    arguments_hash,
    compute_idempotency_key,
)


class ToolError(ValueError):
    """A permanent tool failure that should not be retried."""

    code: ClassVar[str] = "tool_error"


class ToolTransientError(RuntimeError):
    """A temporary tool failure that may be retried safely."""

    code: ClassVar[str] = "tool_transient_error"


class ToolTimeoutError(ToolTransientError):
    """A tool exceeded its configured execution timeout."""

    code = "tool_timeout"


@dataclass(slots=True, frozen=True)
class ToolPolicy:
    """Execution policy declared by one tool.

    ``None`` values inherit the registry defaults. This lets a tool override only
    the property it cares about without duplicating global execution policy.
    ``sensitive_arguments`` lists parameter names whose values must never appear
    in events, persisted records, or logs; the registry replaces them with ``***``.
    """

    read_only: bool = True
    max_attempts: int | None = None
    timeout_seconds: float | None = None
    retry_base_delay_seconds: float | None = None
    retry_max_delay_seconds: float | None = None
    sensitive_arguments: tuple[str, ...] = ()

    def __post_init__(self) -> None:
        for field_name in self.sensitive_arguments:
            if not isinstance(field_name, str) or not field_name:
                raise ValueError("sensitive_arguments must be non-empty strings")


@dataclass(slots=True, frozen=True)
class ToolExecutionDefaults:
    """Registry-wide defaults for retries and timeouts."""

    max_attempts: int = 3
    timeout_seconds: float = 30.0
    retry_base_delay_seconds: float = 0.2
    retry_max_delay_seconds: float = 2.0

    def __post_init__(self) -> None:
        if self.max_attempts < 1:
            raise ValueError("max_attempts must be at least 1")
        if self.timeout_seconds <= 0:
            raise ValueError("timeout_seconds must be positive")
        if self.retry_base_delay_seconds < 0:
            raise ValueError("retry_base_delay_seconds cannot be negative")
        if self.retry_max_delay_seconds < self.retry_base_delay_seconds:
            raise ValueError("retry_max_delay_seconds cannot be smaller than the base delay")


@dataclass(slots=True, frozen=True)
class ToolContext:
    """Runtime context that is not generated by the model."""

    session_id: str = ""
    user_id: str = ""
    is_admin: bool = False
    knowledge_bases: tuple[str, ...] = ()
    turn_id: str = ""


@dataclass(slots=True)
class ToolResult:
    content: str
    success: bool = True
    metadata: dict[str, Any] | None = None


class BaseTool(ABC):
    """A model-callable unit with metadata and one execution method."""

    name: ClassVar[str]
    description: ClassVar[str]
    parameters: ClassVar[dict[str, Any]]
    policy: ClassVar[ToolPolicy] = ToolPolicy()

    def schema(self) -> dict[str, Any]:
        return {
            "type": "function",
            "function": {
                "name": self.name,
                "description": self.description,
                "parameters": self.parameters,
            },
        }

    @abstractmethod
    async def execute(
        self,
        context: ToolContext | None = None,
        **kwargs: Any,
    ) -> ToolResult:
        raise NotImplementedError


class CalculatorTool(BaseTool):
    name = "calculator"
    description = "Evaluate a basic arithmetic expression safely."
    parameters = {
        "type": "object",
        "properties": {
            "expression": {
                "type": "string",
                "description": "Arithmetic expression using +, -, *, /, and parentheses.",
            }
        },
        "required": ["expression"],
        "additionalProperties": False,
    }
    policy = ToolPolicy(read_only=True, max_attempts=1, timeout_seconds=2.0)

    _binary_operators: ClassVar[dict[type[ast.operator], Any]] = {
        ast.Add: operator.add,
        ast.Sub: operator.sub,
        ast.Mult: operator.mul,
        ast.Div: operator.truediv,
        ast.Mod: operator.mod,
        ast.Pow: operator.pow,
    }
    _unary_operators: ClassVar[dict[type[ast.unaryop], Any]] = {
        ast.UAdd: operator.pos,
        ast.USub: operator.neg,
    }

    async def execute(
        self,
        context: ToolContext | None = None,
        **kwargs: Any,
    ) -> ToolResult:
        del context
        expression = str(kwargs.get("expression") or "").strip()
        if not expression:
            raise ToolError("expression is required")
        try:
            tree = ast.parse(expression, mode="eval")
            value = self._evaluate(tree.body)
        except (SyntaxError, TypeError, ZeroDivisionError, ToolError) as exc:
            raise ToolError(f"invalid expression: {exc}") from exc
        return ToolResult(content=str(value), metadata={"expression": expression})

    def _evaluate(self, node: ast.AST) -> int | float:
        if isinstance(node, ast.Constant) and isinstance(node.value, (int, float)):
            return node.value
        if isinstance(node, ast.BinOp) and type(node.op) in self._binary_operators:
            return self._binary_operators[type(node.op)](
                self._evaluate(node.left),
                self._evaluate(node.right),
            )
        if isinstance(node, ast.UnaryOp) and type(node.op) in self._unary_operators:
            return self._unary_operators[type(node.op)](self._evaluate(node.operand))
        raise ToolError(f"unsupported syntax: {type(node).__name__}")


class KnowledgeSearchTool(BaseTool):
    name = "knowledge_search"
    description = (
        "Search the learner's selected knowledge bases and return relevant "
        "source snippets with citations."
    )
    parameters = {
        "type": "object",
        "properties": {
            "query": {
                "type": "string",
                "description": "A focused natural-language search query.",
            },
            "knowledge_bases": {
                "type": "array",
                "items": {"type": "string"},
                "description": "Optional knowledge base names. Omit to use the current selection.",
            },
            "limit": {
                "type": "integer",
                "minimum": 1,
                "maximum": 10,
                "description": "Maximum number of source snippets.",
            },
        },
        "required": ["query"],
        "additionalProperties": False,
    }
    policy = ToolPolicy(read_only=True, max_attempts=3, timeout_seconds=10.0)

    def __init__(self, service: KnowledgeService) -> None:
        self.service = service

    async def execute(
        self,
        context: ToolContext | None = None,
        **kwargs: Any,
    ) -> ToolResult:
        query = str(kwargs.get("query") or "").strip()
        if not query:
            raise ToolError("query is required")
        requested_bases = kwargs.get("knowledge_bases")
        if isinstance(requested_bases, list):
            knowledge_bases = [str(name) for name in requested_bases]
        else:
            knowledge_bases = list(context.knowledge_bases if context else ())
        limit = int(kwargs.get("limit") or 5)
        try:
            hits = await self.service.search(
                query,
                knowledge_bases,
                limit=limit,
                owner_id=context.user_id if context else "",
                is_admin=context.is_admin if context else False,
            )
        except sqlite3.OperationalError as exc:
            if not _is_transient_sqlite_error(exc):
                raise
            raise ToolTransientError("知识库暂时不可用，请稍后重试") from exc
        except (TimeoutError, OSError) as exc:
            raise ToolTransientError("知识库暂时不可用，请稍后重试") from exc
        if not hits:
            return ToolResult(
                content=(
                    "知识库中没有找到与该问题相关的资料。"
                    "可以建议学习者换一种说法（尽量用资料里的术语），"
                    "或确认已选中正确的知识库。"
                ),
                metadata={"sources": [], "query": query},
            )

        formatted = []
        sources = []
        widened = any(hit.metadata.get("widened_bases") for hit in hits)
        for index, hit in enumerate(hits, start=1):
            citation = f"{hit.document} · 片段 {hit.chunk_index + 1}"
            formatted.append(
                f"[{index}] 知识库：{hit.knowledge_base}\n来源：{citation}\n内容：{hit.content}"
            )
            sources.append(
                {
                    "id": f"{hit.knowledge_base}:{hit.document}:{hit.chunk_index}",
                    "title": hit.document,
                    "knowledge_base": hit.knowledge_base,
                    "chunk_index": hit.chunk_index,
                    "snippet": hit.content,
                    "score": hit.score,
                    "retrievers": hit.metadata.get("retrievers", []),
                }
            )
        content = "\n\n---\n\n".join(formatted)
        if widened:
            # 空结果回退扩大了检索范围,如实告知模型,由它向学习者说明。
            content += (
                "\n\n(注:选中的知识库没有直接命中,以上结果来自自动扩大范围后"
                "该学习者的其他知识库。)"
            )
        return ToolResult(
            content=content,
            metadata={"sources": sources, "query": query},
        )


class SaveToKnowledgeBaseTool(BaseTool):
    """把用户在对话中给出的题目/笔记沉淀进其学科知识库(P3 后的"沉淀罐"能力)。

    学生的真实痛点:作业散落在系统里,期末没题可复习。这个工具让聊天框
    变成收集箱——"把这道题存进微积分基础：..."一句话落库,带日期与来源
    标记,期末即可从库里生成复习材料。落库属写操作:保守政策(串行、
    不重试),owner 边界与上传接口完全一致(他人的同名库不可写)。
    """

    name = "save_to_knowledge_base"
    description = (
        "当用户明确要求把一道题目、笔记或一段内容保存/沉淀进某个知识库时调用。"
        "content 应保存用户提供的完整原文(题目+必要上下文),不要缩写或改写。"
        "knowledge_base 填用户指定的库名;未指定时先追问,不要猜。"
    )
    parameters = {
        "type": "object",
        "properties": {
            "knowledge_base": {
                "type": "string",
                "description": "目标知识库名称,如'微积分基础'。",
            },
            "title": {
                "type": "string",
                "description": "这份资料的简短标题,如'作业:极限计算题'。",
            },
            "content": {
                "type": "string",
                "description": "要保存的完整原文,保留题目条件与用户的疑问。",
            },
        },
        "required": ["knowledge_base", "title", "content"],
        "additionalProperties": False,
    }
    policy = ToolPolicy(read_only=False, max_attempts=1, timeout_seconds=10.0)

    def __init__(self, service: KnowledgeService) -> None:
        self.service = service

    async def execute(
        self,
        context: ToolContext | None = None,
        **kwargs: Any,
    ) -> ToolResult:
        knowledge_base = str(kwargs.get("knowledge_base") or "").strip()
        title = str(kwargs.get("title") or "").strip()
        content = str(kwargs.get("content") or "").strip()
        if not knowledge_base or not title or not content:
            raise ToolError("knowledge_base、title、content 都是必填项")
        owner_id = context.user_id if context else ""
        if not owner_id:
            raise ToolError("需要登录后才能沉淀内容")
        dated = (
            f"# {title}\n\n"
            f"> 沉淀于 {time.strftime('%Y-%m-%d')} · 来自对话\n\n{content}\n"
        )
        result = await self.service.add_document(
            knowledge_base,
            f"{title}.md",
            dated.encode("utf-8"),
            owner_id=owner_id,
            is_admin=context.is_admin if context else False,
        )
        return ToolResult(
            content=(
                f"已存入知识库「{knowledge_base}」：《{title}》"
                f"（{result.chunks} 个片段）。期末复习时可以从这个库生成练习题。"
            ),
            metadata={
                "knowledge_base": knowledge_base,
                "document": result.filename,
                "chunks": result.chunks,
                "saved": True,
            },
        )


class ToolRegistry:
    def __init__(
        self,
        defaults: ToolExecutionDefaults | None = None,
        execution_store: ToolExecutionStore | None = None,
        idempotency_enabled: bool = True,
        redaction_enabled: bool = True,
    ) -> None:
        self._tools: dict[str, BaseTool] = {}
        self.defaults = defaults or ToolExecutionDefaults()
        self.execution_store = execution_store
        self.idempotency_enabled = idempotency_enabled
        self.redaction_enabled = redaction_enabled

    def register(self, tool: BaseTool) -> None:
        self._tools[tool.name] = tool

    def get(self, name: str) -> BaseTool | None:
        return self._tools.get(name)

    def names(self) -> list[str]:
        """全部已注册工具名(含 MCP 桥接的动态工具)。"""
        return list(self._tools.keys())

    def is_read_only(self, name: str) -> bool:
        """Whether one tool declares itself safe for bounded concurrency.

        Unknown tools answer ``False`` so the runtime schedules them serially:
        executing an unregistered call concurrently is never required, and the
        conservative default cannot produce duplicate side effects.
        """
        tool = self.get(name)
        return bool(tool.policy.read_only) if tool is not None else False

    def schemas(self, enabled: list[str] | None = None) -> list[dict[str, Any]]:
        names = enabled if enabled is not None else list(self._tools)
        return [self._tools[name].schema() for name in names if name in self._tools]

    async def execute(
        self,
        name: str,
        arguments: dict[str, Any],
        context: ToolContext | None = None,
        call_id: str = "",
    ) -> ToolResult:
        tool = self.get(name)
        if tool is None:
            return ToolResult(
                content=f"Unknown tool: {name}",
                success=False,
                metadata={
                    "attempt_count": 0,
                    "retry_count": 0,
                    "error_code": "unknown_tool",
                    "retryable": False,
                    "duration_ms": 0.0,
                },
            )

        policy = self._resolve_policy(tool)
        idempotency_key = await self._claim_execution(
            tool.name,
            arguments,
            context,
            call_id,
            policy,
        )
        if isinstance(idempotency_key, ToolResult):
            return idempotency_key

        result = await self._execute_with_policy(name, tool, arguments, context, policy)
        if self.redaction_enabled and policy["sensitive_arguments"]:
            result = self._redact_result_metadata(result, policy["sensitive_arguments"])
        if idempotency_key:
            result = self._with_idempotency_metadata(result, idempotency_key)
            await self._persist_execution(idempotency_key, result)
        return result

    def redacted_arguments(
        self,
        name: str,
        arguments: dict[str, Any],
    ) -> dict[str, Any]:
        """Arguments safe for events, records, and logs.

        The Agent Loop uses this when emitting ``tool_call`` events; the raw
        arguments still go to the tool and the model unchanged.
        """
        tool = self.get(name)
        if tool is None or not self.redaction_enabled:
            return dict(arguments)
        policy = self._resolve_policy(tool)
        return redact_arguments(arguments, policy["sensitive_arguments"])

    @staticmethod
    def _redact_result_metadata(
        result: ToolResult,
        sensitive_fields: tuple[str, ...],
    ) -> ToolResult:
        """Mask metadata keys that echo a declared sensitive argument name.

        This is a defensive sweep for tools that copy an argument (for example
        ``api_key``) back into their result metadata; without it the value
        would leak into events and the ``tool_executions`` record.
        """
        metadata = dict(result.metadata or {})
        changed = False
        for field_name in sensitive_fields:
            if field_name in metadata:
                metadata[field_name] = REDACTED_VALUE
                changed = True
        if not changed:
            return result
        return ToolResult(
            content=result.content,
            success=result.success,
            metadata=metadata,
        )

    async def _claim_execution(
        self,
        name: str,
        arguments: dict[str, Any],
        context: ToolContext | None,
        call_id: str,
        policy: dict[str, Any],
    ) -> str | ToolResult:
        """Return the idempotency key when this call owns the execution.

        A ``ToolResult`` return value means the call must not execute the tool:
        either the stored result is replayed or the execution is still running.
        An empty string means idempotency is not engaged (no store, disabled,
        or no turn identity), which keeps direct registry calls unchanged.
        """
        store = self.execution_store
        if (
            store is None
            or not self.idempotency_enabled
            or context is None
            or not context.turn_id
        ):
            return ""
        idempotency_key = compute_idempotency_key(
            user_id=context.user_id,
            session_id=context.session_id,
            turn_id=context.turn_id,
            call_id=call_id,
            tool_name=name,
            arguments=arguments,
        )
        claim = await store.begin(
            idempotency_key=idempotency_key,
            user_id=context.user_id,
            session_id=context.session_id,
            turn_id=context.turn_id,
            call_id=call_id,
            tool_name=name,
            arguments_hash=arguments_hash(arguments),
            read_only=bool(policy["read_only"]),
        )
        if claim.claimed:
            return idempotency_key
        record = claim.record
        if record is not None and record.status == "running":
            record = await store.wait_for_terminal(idempotency_key)
        if record is None or record.status == "running":
            return self._in_progress_result(name, idempotency_key)
        return self._replay_result(record)

    async def _persist_execution(self, idempotency_key: str, result: ToolResult) -> None:
        store = self.execution_store
        if store is None:
            return
        metadata = result.metadata or {}
        if result.success:
            await store.complete(
                idempotency_key,
                result_content=result.content,
                result_metadata=metadata,
                attempt_count=int(metadata.get("attempt_count", 0)),
            )
        else:
            await store.fail(
                idempotency_key,
                error_content=result.content,
                result_metadata=metadata,
                attempt_count=int(metadata.get("attempt_count", 0)),
            )

    @staticmethod
    def _with_idempotency_metadata(
        result: ToolResult,
        idempotency_key: str,
    ) -> ToolResult:
        metadata = dict(result.metadata or {})
        metadata.update(
            {
                "deduplicated": False,
                "replayed": False,
                "idempotency_key_hash": idempotency_key[:16],
                "execution_status": "completed" if result.success else "failed",
            }
        )
        return ToolResult(
            content=result.content,
            success=result.success,
            metadata=metadata,
        )

    @staticmethod
    def _replay_result(record: ToolExecutionRecord) -> ToolResult:
        metadata = dict(record.result_metadata)
        metadata.update(
            {
                "deduplicated": True,
                "replayed": True,
                "idempotency_key_hash": record.idempotency_key[:16],
                "execution_status": record.status,
                "attempt_count": record.attempt_count,
            }
        )
        if record.status == "completed":
            return ToolResult(
                content=record.result_content,
                success=True,
                metadata=metadata,
            )
        metadata.setdefault("error_code", "tool_execution_failed")
        metadata.setdefault("retryable", False)
        metadata.setdefault("timed_out", False)
        content = record.error_content or f"Tool {record.tool_name} failed"
        return ToolResult(content=content, success=False, metadata=metadata)

    @staticmethod
    def _in_progress_result(name: str, idempotency_key: str) -> ToolResult:
        return ToolResult(
            content=f"Tool {name} is still executing; try the request again later.",
            success=False,
            metadata={
                "deduplicated": True,
                "replayed": False,
                "idempotency_key_hash": idempotency_key[:16],
                "execution_status": "running",
                "error_code": "tool_execution_in_progress",
                "retryable": True,
                "timed_out": False,
            },
        )

    async def _execute_with_policy(
        self,
        name: str,
        tool: BaseTool,
        arguments: dict[str, Any],
        context: ToolContext | None,
        policy: dict[str, Any],
    ) -> ToolResult:
        started_at = time.perf_counter()
        attempt_count = 0
        retry_delays_ms: list[float] = []
        last_error: Exception | None = None
        timed_out = False

        while attempt_count < policy["max_attempts"]:
            attempt_count += 1
            try:
                result = await asyncio.wait_for(
                    tool.execute(context=context, **arguments),
                    timeout=policy["timeout_seconds"],
                )
                return self._with_execution_metadata(
                    result,
                    attempt_count=attempt_count,
                    retry_delays_ms=retry_delays_ms,
                    duration_ms=(time.perf_counter() - started_at) * 1000,
                    policy=policy,
                )
            except TimeoutError as exc:
                timed_out = True
                last_error = ToolTimeoutError(
                    f"Tool {name} timed out after {policy['timeout_seconds']:.2f}s"
                )
                last_error.__cause__ = exc
            except ToolTransientError as exc:
                last_error = exc
            except ToolError as exc:
                return self._failure_result(
                    name,
                    exc,
                    attempt_count=attempt_count,
                    retry_delays_ms=retry_delays_ms,
                    duration_ms=(time.perf_counter() - started_at) * 1000,
                    policy=policy,
                    retryable=False,
                    timed_out=False,
                )
            except Exception as exc:  # unknown failures are treated as permanent
                return self._failure_result(
                    name,
                    exc,
                    attempt_count=attempt_count,
                    retry_delays_ms=retry_delays_ms,
                    duration_ms=(time.perf_counter() - started_at) * 1000,
                    policy=policy,
                    retryable=False,
                    timed_out=False,
                )

            if attempt_count >= policy["max_attempts"]:
                break
            delay_seconds = min(
                policy["retry_max_delay_seconds"],
                policy["retry_base_delay_seconds"] * (2 ** (attempt_count - 1)),
            )
            retry_delays_ms.append(round(delay_seconds * 1000, 2))
            if delay_seconds > 0:
                await asyncio.sleep(delay_seconds)

        assert last_error is not None
        return self._failure_result(
            name,
            last_error,
            attempt_count=attempt_count,
            retry_delays_ms=retry_delays_ms,
            duration_ms=(time.perf_counter() - started_at) * 1000,
            policy=policy,
            retryable=True,
            timed_out=timed_out,
        )

    def _resolve_policy(self, tool: BaseTool) -> dict[str, Any]:
        policy = tool.policy
        max_attempts = (
            policy.max_attempts
            if policy.max_attempts is not None
            else self.defaults.max_attempts
        )
        timeout_seconds = (
            policy.timeout_seconds
            if policy.timeout_seconds is not None
            else self.defaults.timeout_seconds
        )
        retry_base_delay_seconds = (
            policy.retry_base_delay_seconds
            if policy.retry_base_delay_seconds is not None
            else self.defaults.retry_base_delay_seconds
        )
        retry_max_delay_seconds = (
            policy.retry_max_delay_seconds
            if policy.retry_max_delay_seconds is not None
            else self.defaults.retry_max_delay_seconds
        )
        if max_attempts < 1:
            raise ValueError("tool max_attempts must be at least 1")
        if timeout_seconds <= 0:
            raise ValueError("tool timeout_seconds must be positive")
        if retry_base_delay_seconds < 0 or retry_max_delay_seconds < 0:
            raise ValueError("tool retry delays cannot be negative")
        return {
            "read_only": policy.read_only,
            "max_attempts": max_attempts,
            "timeout_seconds": timeout_seconds,
            "retry_base_delay_seconds": retry_base_delay_seconds,
            "retry_max_delay_seconds": max(
                retry_base_delay_seconds,
                retry_max_delay_seconds,
            ),
            "sensitive_arguments": policy.sensitive_arguments,
        }

    def _with_execution_metadata(
        self,
        result: ToolResult,
        *,
        attempt_count: int,
        retry_delays_ms: list[float],
        duration_ms: float,
        policy: dict[str, Any],
    ) -> ToolResult:
        metadata = dict(result.metadata or {})
        metadata.update(
            {
                "attempt_count": attempt_count,
                "retry_count": max(0, attempt_count - 1),
                "retry_delays_ms": retry_delays_ms,
                "duration_ms": round(duration_ms, 2),
                "read_only": policy["read_only"],
                "max_attempts": policy["max_attempts"],
                "timeout_seconds": policy["timeout_seconds"],
            }
        )
        return ToolResult(
            content=result.content,
            success=result.success,
            metadata=metadata,
        )

    def _failure_result(
        self,
        name: str,
        error: Exception,
        *,
        attempt_count: int,
        retry_delays_ms: list[float],
        duration_ms: float,
        policy: dict[str, Any],
        retryable: bool,
        timed_out: bool,
    ) -> ToolResult:
        error_code = str(getattr(error, "code", "tool_error"))
        metadata = {
            "attempt_count": attempt_count,
            "retry_count": max(0, attempt_count - 1),
            "retry_delays_ms": retry_delays_ms,
            "duration_ms": round(duration_ms, 2),
            "error_code": error_code,
            "retryable": retryable,
            "timed_out": timed_out,
            "read_only": policy["read_only"],
            "max_attempts": policy["max_attempts"],
            "timeout_seconds": policy["timeout_seconds"],
        }
        return ToolResult(
            content=f"Tool {name} failed: {error}",
            success=False,
            metadata=metadata,
        )


def build_default_registry(
    knowledge_service: KnowledgeService,
    *,
    defaults: ToolExecutionDefaults | None = None,
    execution_store: ToolExecutionStore | None = None,
    idempotency_enabled: bool = True,
    redaction_enabled: bool = True,
) -> ToolRegistry:
    registry = ToolRegistry(
        defaults,
        execution_store=execution_store,
        idempotency_enabled=idempotency_enabled,
        redaction_enabled=redaction_enabled,
    )
    registry.register(CalculatorTool())
    registry.register(KnowledgeSearchTool(knowledge_service))
    registry.register(SaveToKnowledgeBaseTool(knowledge_service))
    return registry


def _is_transient_sqlite_error(error: sqlite3.OperationalError) -> bool:
    message = str(error).lower()
    return any(
        marker in message
        for marker in ("locked", "busy", "timeout", "temporarily", "unable to open")
    )


REDACTED_VALUE = "***"


def redact_arguments(
    arguments: dict[str, Any],
    sensitive_fields: tuple[str, ...],
) -> dict[str, Any]:
    """Return a copy of arguments with declared sensitive values masked.

    Only top-level field names declared by the tool are masked. The raw
    arguments must still reach the tool itself and the model; redaction is
    for observability surfaces (events, records, logs) only.
    """
    redacted = dict(arguments)
    for field_name in sensitive_fields:
        if field_name in redacted:
            redacted[field_name] = REDACTED_VALUE
    return redacted
